### ISSUE TITLE
README example fails

### ISSUE THREAD

**Issue by john-aws** [jmespath/jp#22] opened 2020-02-19 18:38 UTC
The README includes the following example:

```
$ echo '{"foo": {"bar": ["a", "b", "c"]}}' | jp foo.bar[1]
"b"

```

On Mac, this fails as follows:

```
$ echo '{"foo": {"bar": ["a", "b", "c"]}}' | jp foo.bar[1]
2020/02/19 10:35:50 line.go:44: no valid y values given
```

**Comment by curiositycasualty** [comment] 2020-03-05 23:54
see also https://github.com/jmespath/jp/issues/17

**Comment by jamesls** [comment] 2021-09-29 19:18
Should be fixed now, installation instructions have been updated.

**Closed as completed by jamesls** 2021-09-29 19:18 UTC

**Comment by john-aws** [comment] 2021-11-17 19:00
Interesting that the current release at [GitHub](https://github.com/jmespath/jp/releases) is 0.2.1 and the current release available from brew is 0.2.0, yet my previously-installed local version of `jp` (originally installed via brew in Feb 2020) is allegedly 1.1.2:

```
$ brew install jmespath/jmespath/jp
Error: jp 1.1.12 is already installed
To install 0.2.0, first run:
  brew unlink jp
```

**Comment by robikarobika** [comment] 2022-04-15 22:24
```
% brew install jmespath/jmespath/jp
==> Tapping jmespath/jmespath
Cloning into '/usr/local/Homebrew/Library/Taps/jmespath/homebrew-jmespath'...
remote: Enumerating objects: 45, done.
remote: Total 45 (delta 0), reused 0 (delta 0), pack-reused 45
Unpacking objects: 100% (45/45), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/jmespath/homebrew-jmespath/Formula/jp.rb
jp: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the jmespath/jmespath tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/jmespath/homebrew-jmespath/Formula/jp.rb:8

Error: Cannot tap jmespath/jmespath: invalid syntax in tap!
```

**Comment by curiositycasualty** [comment] 2022-04-21 18:52
@robikarobika Seems like a duplicate of https://github.com/jmespath/homebrew-jmespath/issues/3

**Comment by mroswell** [comment] 2023-06-06 05:46
A new install tonight on a MacBook, and I get this:
```
% echo '{"key": "value"}' | jp key
"value"
```
```
% echo '{"foo": {"bar": ["a", "b", "c"]}}' | jp foo.bar[1]
zsh: no matches found: foo.bar[1]
```
```
% echo '{"foo": {"bar": ["a", "b", "c"]}}' | jp foo.bar
[
  "a",
  "b",
  "c"
]
```

Any fixes for the second result?
